/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package referenced.lib;

public class AppReferenced {
    public String getGreeting() {
        return "Hello World from referenced!";
    }

    public static void main(String[] args) {
        System.out.println(new AppReferenced().getGreeting());
    }
}
