/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package referenced.lib;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        AppReferenced classUnderTest = new AppReferenced();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
